---
- name: Proxmox spawn test
  hosts: proxmox_clients

  vars_files:
    - "vars/secrets.yml"

  tasks:
    - name: Create a test VM
      community.general.proxmox_kvm:
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        api_host: proxmox.estuary.tech
        name: dev-maas-test00
        memory: 2048
        cores: 2
        description: "A test VM spawned by EHI Cloudy Dreams."
        onboot: false
        cpu: host
        node: apollo
        scsi:
          scsi0: 'vm-storage:15,format=raw'
        net:
          net0: 'bridge=vmbr0,virtio,mtu=1,firewall=1'
        bios: ovmf
      efidisk0:
        storage: vm-storage
        format: raw
        efitype: 4m
        pre_enrolled_keys: false

    - name: Start the test VM
      community.general.proxmox_kvm:
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        api_host: proxmox.estuary.tech
        name: dev-maas-test00
        state: started