---
# Machine specs
scsi_disk_layout:
  scsi0: "vm-storage:32,format=raw,discard=on,ssd=1"
amount_of_memory: 8192
number_of_vcpus: 4
ip_range:
  - start: 10.24.0.21
    end: 10.24.0.23
starting_number: 1
vm_name: prod-haproxy
vm_description: "Production HAProxy node"