---
# Machine specs
scsi_disk_layout:
  scsi0: "vm-storage:32,format=raw,discard=on,ssd=1"
amount_of_memory: 6144
number_of_vcpus: 4
ip_range:
  - start: 10.24.3.200
    end: 10.24.3.202
starting_number: 1
vm_name: prod-fwscdn
vm_description: "Production FWS CDN node"
