---
# Machine specs
scsi_disk_layout:
  scsi0: "vm-storage:400,format=raw"
amount_of_memory: 98304
number_of_vcpus: 96
ip_range:
  - start: 10.24.0.90
    end: 10.24.3.97
starting_number: 1
vm_name: prod-ebi-db
vm_description: "Production EBI Delta node"