---
# Machine specs
scsi_disk_layout:
  scsi0: "vm-storage:50,format=raw"
  scsi1: "vm-storage:400,format=raw"
amount_of_memory: 16384
number_of_vcpus: 12
ip_range:
  - start: 10.24.3.20
    end: 10.24.3.22
starting_number: 1
vm_name: prod-ehi-db
vm_description: "Production EHI Database node"