---
# Machine specs
scsi_disk_layout:
  scsi0: "vm-storage:32,format=raw,discard=on,ssd=1"
amount_of_memory: 8192
number_of_vcpus: 6
ip_range:
  - start: 10.24.3.73
    end: 10.24.3.75
starting_number: 1
vm_name: prod-sp-throttler
vm_description: "Production SP Throttler"
