---
# Machine specs
scsi_disk_layout:
  scsi0: "vm-storage:200,format=raw,discard=on,ssd=1"
amount_of_memory: 8192
number_of_vcpus: 6
ip_range:
  - start: 10.24.3.90
    end: 10.24.3.92
starting_number: 1
vm_name: prod-commp-db
vm_description: "Production Commp Database"
