---
# Machine specs
scsi_disk_layout:
  scsi0: "vm-storage:50,format=raw,discard=on,ssd=1"
amount_of_memory: 8192
number_of_vcpus: 4
ip_range:
  - start: 10.24.0.40
    end: 10.24.0.44
starting_number: 1
vm_name: prod-nsqlookupd
vm_description: "Production NSQ nsqlookupd node"
