---
# Machine specs
scsi_disk_layout:
  scsi0: "vm-storage:400,format=raw"
amount_of_memory: 32768
number_of_vcpus: 24
ip_range:
  - start: 10.24.0.30
    end: 10.24.0.32
starting_number: 1
vm_name: prod-ehi-api
vm_description: "Production EHI API node"